global using System.Text;
global using DesignPatterns.SingleResponsibilityPrinciple;
global using DesignPatterns.OpenClosePrinciple;
global using DesignPatterns.LiskovSubstitutionPrinciple;
global using DesignPatterns.InterfaceSegregationPrinciple;
global using DesignPatterns.DependencyInversionPrinciple;
global using DesignPatterns.Builders;